version: '3'

services:
    django-web:
        container_name: blogproject
        image: hsukju00/blogproject
        build: ./blogproject
        volumes:
            - uwsgi_sock:/tmp

    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        env_file:
            - ".env"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - uwsgi_sock:/tmp
        depends_on:
            - django-web

volumes:
    uwsgi_sock:
