name: Deploy to EC2 using SSH

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Add Github Actions Ip to Security Group
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AWS_SSH_HOST }}
        username: ${{ secrets.AWS_SSH_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: ${{ secrets.AWS_SSH_PORT }}
        script_stop: true
        script: |
          cd /srv/hsukju-blog
          git pull
          sudo systemctl daemon-reload
          sudo systemctl restart uwsgi nginx
